FROM camunda/camunda-bpm-platform:latest

# add slf4j bridge
ADD https://search.maven.org/remotecontent?filepath=org/slf4j/slf4j-jdk14/1.7.12/slf4j-jdk14-1.7.12.jar /camunda/lib/slf4j-jdk14.jar

# add dnsjava library
ADD https://search.maven.org/remotecontent?filepath=dnsjava/dnsjava/2.1.7/dnsjava-2.1.7.jar /camunda/lib/dnsjava.jar
